kind = "web"
previewPath = "/"
title = "Drave Registry"
version = "1.0.0"
id = "artifacts/drave-registry"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19644

[services.development]
run = "pnpm --filter @workspace/drave-registry run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/drave-registry", "run", "build" ]
publicDir = "artifacts/drave-registry/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19644"
BASE_PATH = "/"
